### ISSUE TITLE
Simplify db4 installation

### ISSUE THREAD

**Issue by meeDamian** [lncm/dockerfiles#1]
The whole `# Build and Install Berkley DB 4.8.30` block can be replaced with

```
./contrib/install_db4.sh $(pwd)
```

run from the root of bitcoin repo, it also puts berkleydb in the _standard_ location:

```
bitcoin/db4/
```

**Comment by nolim1t** [comment]
Will investigate this option. 

What is the standard location of the berkleydb? just in case the docker container doesn't recognize it?

**Comment by meeDamian** [comment]
As I wrote: `./bitcoin/db4/`

It does exactly the same as your script lines, except it puts it inside the bitcoin directory and is a brain-dead one-liner already bundled-in with bitcoind repository.

**Comment by nolim1t** [comment]
## Notes 

```bash
export BDB_PREFIX='/home/pi/bitcoin/db4'
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
```

**Comment by nolim1t** [comment]
Installation simplified
