### ISSUE TITLE
ENV vars not working

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/dockerfiles#4]
https://github.com/lncm/dockerfiles/blob/9e674c0a370b64bff95bd7d96716fc3cdea04db4/bitcoind/Dockerfile#L44

Hotfix for arm:
`RUN ./configure CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib" --with-boost-libdir=/usr/lib/arm-linux-gnueabihf --without-gui --disable-wallet --prefix=/usr/local/bitcoin --disable-tests --disable-bench`

**Comment by nolim1t** [comment]
Feel free to send a PR put also put the x86 line as a comment down the bottom as well.

It's not the most elegant though. Or maybe have two different docker files

**Comment by nolim1t** [comment]
I've removed all env files and now using individual docker files for building depending on arch (either ARM or x86_64)
