### ISSUE TITLE
Change URLs

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/dockerfiles#5]
Please point official downloads to the appropriate repo in https://hub.docker.com/u/lncm/dashboard/

**Comment by nolim1t** [comment]
Get the irrelephant picture as a lncm gravatar so theres a profile picture.

If you like you may give me the email details and I can set it up. My pgp key is on keybase

**Comment by nolim1t** [comment]
[Done](https://hub.docker.com/r/lncm/bitcoind/tags/)

Because there are issues with lightning in a docker container I Have not put any link yet.
