### ISSUE TITLE
Arch

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/dockerfiles#7]
We can discuss the architecture naming scheme here

**Pi Zero & Pi 1 / Pi 1+**
Single-core ARMv6 (32-bit)

**Pi 2**
Quad-core ARMv7 (32-bit)

**Pi 2 v1.2**
Quad-core ARMv8 (32/64-bit)

**Pi 3**
Quad-core ARMv8 (32/64-bit)

**PC**
x86_64 could be abbreviated to x64.

You can check if your OS is 32/64 bit like so:
`getconf LONG_BIT`

**Comment by nolim1t** [comment]
arm should be arm7 or arm8

x32 or x64 sounds good. will do this onwards

**Comment by AnotherDroog** [comment]
Yes, I also believe ARMv6 is a subset of ARMv7 so they should be compatible.

The only distinction we need is arm7 and arm8

**Comment by nolim1t** [comment]
I think version-arch looks nicer than version_arch

**Comment by meeDamian** [comment]
I think `x32` should be `x86` other than that, perfect
