### ISSUE TITLE
Create arm6 lncm image

### ISSUE THREAD

**Issue by nolim1t** [lncm/dockerfiles#8]
Any volunteers to make a arm6 lncm image... @meeDamian ?

**Comment by nolim1t** [comment]
This is not needed anymore as the overall vision suggests that we do not run anything other than point of sale on the zero

**Comment by meeDamian** [comment]
I'd like to have our generic Bitcoin / ln images avail in all useful architectures. Not for us, just so that other people can use our images w/o using their own...

**Comment by nolim1t** [comment]
Sure if you can get docker to play nice on the zero

**Comment by meeDamian** [comment]
Ah, I forgot there were some issues there, but let's talk about it in more detail later(?)
