### ISSUE TITLE
Migrate from ubuntu to alpine base images

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/dockerfiles#9]

**Comment by meeDamian** [comment]
This looks amazing for bitcoind: https://github.com/ruimarinho/docker-bitcoin-core

I think we can re-use images there except build them for different archs and perhaps remove wallet.

**Comment by meeDamian** [comment]
After a tiny modification (`make -j4` -> `make`) above alpine images completed on both macos and RBP3.

Unfortunately RBP0 run out of memory by the end, so I'll try again after increasing SWAP a little bit. Luckily up until the memory error everything worked flawlessly :D.

**Comment by nolim1t** [comment]
You managed to build bitcoin on docker with the zero? Nice. I Guess alpine worked

**Comment by meeDamian** [comment]
Well, technically I haven't _yet_, although I've increased SWAP from 100mb to 512mb and I'm running it again - I'll post here when/if it completes.

**Comment by meeDamian** [comment]
So… it seems that alpine images do not actually distinguish between RBP 3 & 0 architectures, allowing us to only have one `arm32v6` image.

Said image can be build on a RBP 3, or (needs some further digging) on an `amd64` machine using QEMU emulation.

I've opened the issue in the `bitcoind` repo mentioned above to perhaps get the authors there to start _also_ building/hosting the `arm` arch _(more here: https://github.com/ruimarinho/docker-bitcoin-core/issues/67)_ would be great to avoid duplication of efforts and perhaps start having a sound base `bitcoind` image that's not as disatrously terrible as the top search results on the docker hub…

I've also created a **temporary** repo for the Dockerfile here: https://github.com/meeDamian/bitcoind _(hosting images here: https://hub.docker.com/r/meedamian/bitcoind/tags/)_ the main difference is that it only has `bitcoind v0.17` alpine image, and changes all `RUN make -j4` lines to `RUN make`.

PS. `bitcoind` images produced this way are as tiny as ~20mb(!!) making them insanely perfect for our usecase! :D

**Comment by nolim1t** [comment]
Awesome work.  We only need bitcoind v0.17

**Comment by nolim1t** [comment]
I looked at the docker file and the guy doesn’t even build bitcoin for starters. It’s fine but our images actually allows for people who want to build their own binary.

It’s fine as an option though.

**Comment by meeDamian** [comment]
it does build bitcoin, see: https://github.com/meeDamian/bitcoind/blob/master/Dockerfile#L55-L81

**Comment by AnotherDroog** [comment]
I'm currently investigating if it's realistic to replace the entire Raspbian image (368MB compressed/1.9GB) with Alpine (42MB compressed/53MB)

**Comment by meeDamian** [comment]
Love it! (although this comment probably belongs more to `pi-factory` 😉)

**Comment by AnotherDroog** [comment]
Done
